class Constants {
  static String get apiUrl => 'http://190.111.249.225/RowingAppApi';

  static String get version => '1.0.0';

  static List<String> get cities => [
        'Aguada Guzman',
        'Allen',
        'Arroyo de la Ventana',
        'Arroyo los Berros',
        'Balneario El Condor',
        'Balneario Los Salados',
        'Balsa Las Perlas',
        'Barda del Medio',
        'Campo Grande',
        'Catriel',
        'Cerro Policía',
        'Cervantes',
        'Chelforo',
        'Chichinales',
        'Chimpay',
        'Choele Choel',
        'Cinco Saltos',
        'Cipolletti',
        'Clemente Onelli',
        'Colonia Julia y Echarren',
        'Comallo',
        'Cona Niyeu',
        'Contralmirante Cordero',
        'Contralmirante Guerrico',
        'Coronel Belisle',
        'Darwin',
        'Dina Huapi',
        'El Bolson',
        'El Cain',
        'El Cuy',
        'El Foyel',
        'El Manso',
        'Ferri',
        'General Conesa',
        'General Enrique Godoy',
        'General Fernandez Oro',
        'General Roca',
        'Guardia Mitre',
        'Ingeniero Huergo',
        'Ingeniero Jacobacci',
        'J.J. Gomez',
        'La Loberia',
        'Lago Pellegrini',
        'Lamarque',
        'Las Grutas',
        'Los Menucos',
        'Luis Beltran',
        'Mainque',
        'Mallin Ahogado',
        'Maquinchao',
        'Mencue',
        'Nahuel Niyeu',
        'Ñorquinco',
        'Paso Cordoba',
        'Peñas Blancas',
        'Pilcaniyeu',
        'Playas Doradas',
        'Pomona',
        'Punta Colorada',
        'Ramos Mexia',
        'Rio Chico',
        'Río Colorado',
        'Rio Villegas',
        'San Antonio Este',
        'San Antonio Oeste',
        'San Carlos de Bariloche',
        'San Javier',
        'Sargento Vidal',
        'Sierra Colorada',
        'Sierra Grande',
        'Sierra Paileman',
        'Stefenelli',
        'Valcheta',
        'Valle Azul',
        'Valle Verde',
        'Viedma',
        'Villa Alberdi',
        'Villa Llanquin',
        'Villa Manzano',
        'Villa Mascardi',
        'Villa Regina',
      ];
}
